# Array

# 1-D Array

In [2]:
# one dimensional array
import numpy as np
a =  np.array([5,5,5,])
a

array([5, 5, 5])

In [3]:
# at the end of the element comma dosenot matter
import numpy as np
a =  np.array([5,5,5])
a

array([5, 5, 5])

In [4]:
type(a)

numpy.ndarray

# 2-D Array

In [6]:
# list of lists
# two dimensional array
b = np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
# find the length of array
len(a)

3

In [8]:
len(b)

3

In [9]:
# indexing 
a[0]

5

In [10]:
# for complete array
a[0:]

array([5, 5, 5])

In [11]:
# for complete array too
a

array([5, 5, 5])

In [12]:
b[0]

array([5, 5, 5])

In [13]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Array attributes
## Dimensions are called axis

In [14]:
# 2-axis
# first axis has length 2
# second axis has length 3
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

# How to create an 1-D array

In [15]:
import numpy as np 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

### - Zero array

In [17]:
b = np.zeros(2)
b

array([0., 0.])

### Identity array

In [19]:
c = np.ones(3)
c

array([1., 1., 1.])

### Empty array

In [20]:
d = np.empty(3)
d

array([1., 1., 1.])

### Range of elements

In [23]:
# starting from zero
# last digit is exclusive ie 6 is not included
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

### Specific range of elements

In [24]:
f = np.arange(3,15)
f

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Range of elements with step size

In [25]:
# starting from 3 and interval(step size) is 2
g = np.arange(3, 20, 2)
g

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

### Linearly spaced arrays

In [28]:
# gives us 4 numbers with same difference
h = np.linspace(4, 25, num=4)
h

array([ 4., 11., 18., 25.])

### Specific data types in array

In [30]:
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [31]:
j = np.ones(4, dtype=np.float64)
j

array([1., 1., 1., 1.])

# How to create 2-D array

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# How to create 3-D Array

In [37]:
# making and reshaping 3-D array
# making an array of 0 to 23 whole numbers of 2 by 3 by 4
# 2 matrices 3 rows and 4 column
k = np.arange(24).reshape(2,3,4)
k

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Again Pratice of one, two and three dimensional arrays

In [4]:
import numpy as np
haris = np.array([1,3,5,7,9])
haris

array([1, 3, 5, 7, 9])

In [8]:
rang = np.arange(5)
rang

array([0, 1, 2, 3, 4])

In [10]:
ring = np.arange (3,26)
ring

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25])

In [17]:
diff = np.arange(4,40,3)
diff

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [15]:
space = np.linspace(1,9, 5)
space


array([1., 3., 5., 7., 9.])

In [16]:
spaces = np.linspace(5, 25, num=5)
spaces

array([ 5., 10., 15., 20., 25.])

In [18]:
k = np.ones(6, dtype= np.int8)
k

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [19]:
l = np.ones((4,5))
l

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
m = np.zeros((2,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
n = np.empty((2,4))
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3-D array

In [24]:
s = np.arange(60).reshape(3,4,5)
s

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])