# Numpy practice session

In [1]:
# import this library in j.notebook
import numpy as np

# Creating an array using numpy

## 1-D Arrays

In [2]:
# 1-D array
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [3]:
price = np.array([15,10,5])
price

array([15, 10,  5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[0:]

array([15, 10,  5])

In [8]:
food[1]

'Samosa'

In [9]:
price.mean()

10.0

In [10]:
# zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# ones
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
# Empty
np.empty(5)

array([0., 0., 0., 0., 0.])

In [15]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# specify range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
# specific interval
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [19]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
# line space
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [22]:
# line space can also be used by this command
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [24]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [25]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Functions

In [30]:
# array of integer and float
# every value convert into float
a = np.array([10,20, 25, 30.5, 2.5, 1.5,40])
a

array([10. , 20. , 25. , 30.5,  2.5,  1.5, 40. ])

## Sorting

In [31]:
# sorted in ascending orders
a.sort()
a

array([ 1.5,  2.5, 10. , 20. , 25. , 30.5, 40. ])

In [32]:
b = np.array([15, 5, 0.4, 30,50])
b

array([15. ,  5. ,  0.4, 30. , 50. ])

## Concatinating two arrays

In [34]:
c = np.concatenate((a,b))
c

array([ 1.5,  2.5, 10. , 20. , 25. , 30.5, 40. , 15. ,  5. ,  0.4, 30. ,
       50. ])

In [36]:
c.sort()
c

array([ 0.4,  1.5,  2.5,  5. , 10. , 15. , 20. , 25. , 30. , 30.5, 40. ,
       50. ])

## 2-D Arrays

## Concatinating different arrays

### Concatinate Same dimensional array

In [42]:
a = np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [39]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [44]:
c = np.concatenate((a,b))
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

### Concatinate different dimensional arrays

In [45]:
# we can also concatinate different type of dimensional arrays e.g
x = np.array([[3,6],[9,12]])
x

array([[ 3,  6],
       [ 9, 12]])

In [50]:
y = np.array([[4,5]])
y

array([[4, 5]])

In [57]:
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
d = np.concatenate((a, b.T), axis=1)
d

array([[1, 2, 5],
       [3, 4, 6]])

In [69]:
e = np.concatenate((a, b), axis=None)
e

array([1, 2, 3, 4, 5, 6])

In [77]:
m = np.array([[5,10],[15,20]])
n = np.array([[25,30]])
p = np.concatenate((m, n), axis=0)
p

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [159]:
q = np.concatenate((m, n), axis=1)
q

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [81]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

### find number of dimension

In [83]:
a.ndim

3

In [84]:
b = np.array([[5,7,9],
             [10,11,12],
             [13,14,15]])
3b

array([[ 5,  7,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [85]:
b.ndim

2

### Size of an array

In [86]:
# size+ total no. element in array
a.size

24

### shape of an array

In [87]:
a.shape

(3, 2, 4)

In [89]:
a = np.arange(6) #3*2=6
a

array([0, 1, 2, 3, 4, 5])

### Reshape of an array

In [90]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [91]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
b = np.arange(9) # 3*3
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
c = np.reshape(b, newshape=(1,9))
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

### Convert 1-D array into 2-D array

In [100]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
a.shape # 1-D array

(8,)

In [104]:
# row wise 2D conversion
b = a[np.newaxis,:] 
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [105]:
b.shape # converted into 2-D because order is 1 by 8 

(1, 8)

In [106]:
# column wise 2D conversion
c = a[:, np.newaxis] 
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [107]:
c.shape

(8, 1)

### Indexing

In [112]:
a[2:6]

array([3, 4, 5, 6])

### Algebraic operations in array

In [113]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [114]:
# multiplication
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [115]:
# addition
a+7

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [116]:
# subtraction
a-4

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [117]:
# division
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

### Sum of whole array

In [118]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
a.sum()

36

### Mean of an array

In [120]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [121]:
b.mean()

4.5

In [131]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [150]:
b = a[a < 5]
b

array([1, 2, 3, 4])

In [148]:
c = (a > 5)
a[c]

array([ 6,  7,  8,  9, 10, 11, 12])

In [147]:
d = (a >= 5)
a [d]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [143]:
e = a[a%2==0]
e

array([ 2,  4,  6,  8, 10, 12])

In [144]:
f = a[(a>3) & (a<11)]
f

array([ 4,  5,  6,  7,  8,  9, 10])

### Horizentle and vertical stack

In [152]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [153]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [154]:
# verticle stack
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [156]:
# horizentle stack
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [157]:
# verticle stack
np.vstack((b,a))

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [158]:
# horizentle stack
np.hstack((b,a))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])