# numpy practice session


In [1]:
# import library
import numpy as np

# Creating an array using numpy

In [2]:
# 1-D array
food= np.array(["samoma", "pakora", "raita"])
food

array(['samoma', 'pakora', 'raita'], dtype='<U6')

In [5]:
price = np.array([15, 30, 10])
price

array([15, 30, 10])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [8]:
len(food)

3

In [12]:
len(price)

3

In [13]:
price[0]

15

In [14]:
price[0:]

array([15, 30, 10])

In [15]:
food[1]

'pakora'

In [16]:
price.mean()

18.333333333333332

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
q=np.empty(5)
q

array([1., 1., 1., 1., 1.])

In [22]:
q = np.empty(5)
q

array([1., 1., 1., 1., 1.])

In [24]:
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.67023293e-307, 2.67019320e-306, 2.42092166e-322]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(2,15)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [29]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.linspace(4, 100, num=5)

array([  4.,  28.,  52.,  76., 100.])

In [33]:
# specify your data type
np.ones(5, dtype= np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [34]:
np.ones(10, dtype= np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# functions of array

In [35]:
a= np.array([2, 4, 67, 12.5, 3, 0,])
a

array([ 2. ,  4. , 67. , 12.5,  3. ,  0. ])

In [37]:
a.sort()
a

array([ 0. ,  2. ,  3. ,  4. , 12.5, 67. ])

In [38]:
a.all
a

array([ 0. ,  2. ,  3. ,  4. , 12.5, 67. ])

In [39]:
a.any
a

array([ 0. ,  2. ,  3. ,  4. , 12.5, 67. ])

In [53]:
a.argmax()
a

array([ 0. ,  2. ,  3. ,  4. , 12.5, 67. ])

In [52]:
a.astype
a

array([ 0. ,  2. ,  3. ,  4. , 12.5, 67. ])

In [45]:
b = np.array([12, 13, 3, 5.4, 3.9 ,0])
b

array([12. , 13. ,  3. ,  5.4,  3.9,  0. ])

In [47]:
c = np.concatenate((a, b))
c

array([ 0. ,  2. ,  3. ,  4. , 12.5, 67. , 12. , 13. ,  3. ,  5.4,  3.9,
        0. ])

In [49]:
c.sort()
c

array([ 0. ,  0. ,  2. ,  3. ,  3. ,  3.9,  4. ,  5.4, 12. , 12.5, 13. ,
       67. ])

# 2-D array

In [54]:
np.array((2,3))

array([2, 3])

In [56]:
m=np.array([[1,2,3,4,5],[5,4,3,2,1]])
m

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [60]:
n= np.array([[7,8,9,10,11],[11,10,9,8,7]])
n

array([[ 7,  8,  9, 10, 11],
       [11, 10,  9,  8,  7]])

In [73]:
n.ndim

2

In [63]:
q= np.concatenate((m,n))
q

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 7,  8,  9, 10, 11],
       [11, 10,  9,  8,  7]])

In [65]:
q= np.concatenate((m,n), axis=1)
q

array([[ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11],
       [ 5,  4,  3,  2,  1, 11, 10,  9,  8,  7]])

In [66]:
q= np.concatenate((m,n), axis=0)
q

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 7,  8,  9, 10, 11],
       [11, 10,  9,  8,  7]])

In [69]:
a=  np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [72]:
# to find the no. of dimension
a.ndim

3

In [74]:
b= np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
b.ndim

2

In [76]:
# to find no. of elements in array
a.size

24

In [77]:
b.size

9

In [82]:
# shape

a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [81]:
a.shape

(3, 2, 4)

In [83]:
# reshape
a= np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [85]:
b= a.reshape(7,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [86]:
a= np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [87]:
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [91]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [92]:
np.reshape(a, newshape=(1, 8), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7]])

# convert one dimensional into 2 dimensional array

In [93]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
a.shape

(8,)

In [96]:
# row wise 2D conversion
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [97]:
b.shape

(1, 8)

In [100]:
# column wise 2D conversion
c = a[ : , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [101]:
# indexing
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
a[2:7]

array([3, 4, 5, 6, 7])

In [105]:
# multiplication of an array
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [107]:
a+5

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [109]:
a.sum()

36

In [110]:
a.mean()

4.5